# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(971, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(80, 70, 381, 381))
        self.label_1.setText("")
        self.label_1.setPixmap(QtGui.QPixmap("assets/imgs/upload.jpg"))
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(540, 70, 381, 381))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("assets/imgs/result.png"))
        self.label_2.setObjectName("label_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(420, 500, 111, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 500, 111, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.uploadPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.uploadPushButton.setGeometry(QtCore.QRect(200, 500, 111, 51))
        self.uploadPushButton.setObjectName("uploadPushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 971, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actiontest = QtWidgets.QAction(MainWindow)
        self.actiontest.setObjectName("actiontest")
        self.actionvedio = QtWidgets.QAction(MainWindow)
        self.actionvedio.setObjectName("actionvedio")
        self.menu.addAction(self.actiontest)
        self.menu_2.addAction(self.actionvedio)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_3.setText(_translate("MainWindow", "火焰识别"))
        self.pushButton_2.setText(_translate("MainWindow", "通用识别"))
        self.uploadPushButton.setText(_translate("MainWindow", "上传图片"))
        self.menu.setTitle(_translate("MainWindow", "图像识别"))
        self.menu_2.setTitle(_translate("MainWindow", "视频识别"))
        self.actiontest.setText(_translate("MainWindow", "test"))
        self.actionvedio.setText(_translate("MainWindow", "vedio"))
