# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Vedio.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1008, 764)
        self.camera = QtWidgets.QRadioButton(Form)
        self.camera.setGeometry(QtCore.QRect(1570, 530, 171, 41))
        self.camera.setAutoFillBackground(True)
        self.camera.setObjectName("camera")
        self.frame_label = QtWidgets.QLabel(Form)
        self.frame_label.setGeometry(QtCore.QRect(820, 590, 951, 541))
        self.frame_label.setAutoFillBackground(True)
        self.frame_label.setText("")
        self.frame_label.setObjectName("frame_label")
        self.camera_2 = QtWidgets.QRadioButton(Form)
        self.camera_2.setGeometry(QtCore.QRect(690, 30, 171, 41))
        self.camera_2.setAutoFillBackground(True)
        self.camera_2.setObjectName("camera_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(240, 30, 361, 31))
        self.label_2.setAutoFillBackground(True)
        self.label_2.setObjectName("label_2")
        self.frame_label_2 = QtWidgets.QLabel(Form)
        self.frame_label_2.setGeometry(QtCore.QRect(30, 90, 931, 551))
        self.frame_label_2.setAutoFillBackground(True)
        self.frame_label_2.setText("")
        self.frame_label_2.setObjectName("frame_label_2")
        self.video_input_2 = QtWidgets.QPushButton(Form)
        self.video_input_2.setGeometry(QtCore.QRect(50, 30, 121, 31))
        self.video_input_2.setObjectName("video_input_2")
        self.det = QtWidgets.QPushButton(Form)
        self.det.setGeometry(QtCore.QRect(250, 670, 181, 71))
        self.det.setObjectName("det")
        self.det_2 = QtWidgets.QPushButton(Form)
        self.det_2.setGeometry(QtCore.QRect(460, 670, 181, 71))
        self.det_2.setObjectName("det_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.camera.setText(_translate("Form", "摄像头输入"))
        self.camera_2.setText(_translate("Form", "摄像头输入"))
        self.label_2.setText(_translate("Form", "空"))
        self.video_input_2.setText(_translate("Form", "视频文件输入"))
        self.det.setText(_translate("Form", "开始检测"))
        self.det_2.setText(_translate("Form", "停止检测"))
